name: Perseus Build

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Select Region'
        required: true
        type: choice
        options:
          - 'EN'
          - 'JP'
          - 'KR'
          - 'TW'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b

      # libPerseus build process
      - name: checkout Perseus
        uses: actions/checkout@v3
        with:
          repository: "n0k0m3/Perseus"
          path: "Perseus"
          ref: "src"

      - name: run Perseus build
        run: |
          cd Perseus
          ./build.sh

      # APK build process
      - name: Determine Bundle ID
        id: bundle_id
        run: |
          case "${{ github.event.inputs.region }}" in
          "EN")
            echo "BUNDLE_ID=com.YoStarEN.AzurLane" >> $GITHUB_ENV
            ;;
          "JP")
            echo "BUNDLE_ID=com.YoStarJP.AzurLane" >> $GITHUB_ENV
            ;;
          "KR")
            echo "BUNDLE_ID=kr.txwy.and.blhx" >> $GITHUB_ENV
            ;;
          "TW")
            echo "BUNDLE_ID=com.hkmanjuu.azurlane.gp" >> $GITHUB_ENV
            ;;
          esac
        shell: bash

      - name: Build Perseus APK
        run: ./patch_perseus.sh ${{ env.BUNDLE_ID }}

      - name: Zipalign and Sign Android release
        run: ./zipalign_sign.sh
                    
      # Publish APK
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Perseus Release ${{ github.event.inputs.region }} v${{ env.PERSEUS_VERSION }}"
          files: |
            build/*.apk